project:
  type: book

execute:
  freeze: auto

engine: jupyter

book:
  title: "数据驱动的可重复性研究"
  subtitle: "Data Driven Reproducible Study"
  author: "高春辉"
  date: now
  cover-image: cover.png
  repo-url: https://github.com/D2RS-2025spring/data-driven-reproducible-study
  issue-url: https://github.com/D2RS-2025spring/data-driven-reproducible-study/issues/
  repo-actions: [edit, source, issue]
  chapters:
    - index.qmd
    - part: 课程简介
      chapters:
        - what-is-reproducible-study.qmd
        - project-introduction.qmd
    - part: 环境搭建
      chapters:
        - reproducible-data-analysis-environment.qmd
        - setup-a-reproducible-environment.qmd
    - part: 基础知识
      chapters:
        - literate-programming.qmd
        - cli.qmd
        - r-basic.qmd
        - python-basic.qmd
        - python-vs-r.qmd
        - git-basic.qmd
    - part: 分组数据分析
      chapters:
        - grouped-data-analysis.qmd
        - grouped-data-analysis-in-action.qmd
        - score-analysis.qmd
    - part: 转录组数据分析
      chapters:
        - transcriptomics-data-analysis-and-visualization.qmd
        - transcriptomics-data-analysis-in-action.qmd
    - part: 微生物组数据分析
      chapters:
        - microbiome-data-analysis-and-visualization.qmd
    - part: 大模型API调用
      chapters:
        - how-to-get-api-key.qmd
        - reading-paper.qmd
        - bailian.qmd
        - huggingface.qmd
        - chatanywhere.qmd
        - deepseek.qmd
    - part: 从零开始神经网络
      chapters:
        - neural-network-from-scratch.qmd
        - two-dimensional-classification.qmd
    - part: 机器学习
      chapters:
        - machine-learning-algorithms-and-implementation.qmd
    - part: 拉曼光谱识别病原菌
      chapters:
        - pathogen-identification-with-raman-spectroscopy.qmd
        - bacteria-id-annotation.qmd
        - pretrained-model.qmd
    - part: 计算机视觉分析实验图片
      chapters:
        - computer-vision-image-analysis.qmd
        - segveg-data-preparation.qmd
        - segveg-model-training.qmd
        #- segveg-model-evaluation.qmd
    - part: 开发协作
      chapters:
        - collaboration-with-global-developers.qmd
        - r-package-development.qmd      
    - part: 问题解答
      chapters:
        - FAQ.qmd
    - references.qmd
  appendices:
    - markdown.qmd
    - write-math-equation.qmd
    - quarto-cheatsheet.qmd
    - ggplot2-cheatsheet.qmd
    - dplyr-cheatsheet.qmd

bibliography: [references.bib, packages.bib]



format:
  html:
    theme: cosmo
    css: custom.css
    fig-width: 7
    fig-asp: 0.618
    fig-align: center
    out-width: 100%
    warning: false
    message: false
    include-in-header:
        - ga.html
    include-after-body:
        - giscus.html
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
              <script async src="https://hypothes.is/embed.js"></script>
  pdf:
    documentclass: ctexbook
    papersize: a4
    margin: 1.5cm
    mermaid-format: png
    extract-media: images
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    out-width: 100%
    include-in-header:
          text: |
            \sloppy % 解决中英文混排的断行问题
            \usepackage{ctex} % 中文支持, 用于中文书籍排版
            \usepackage{amsthm,mathrsfs} % 数学支持, 数学字体
            \usepackage{fvextra} % 代码块支持, 代码块中支持断行
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}} % 代码块中支持断行
            \usepackage[version=4]{mhchem} % 化学方程式支持
            \usepackage{siunitx} % 国际单位支持
